module.exports = {
  Property: {
    name: 'Property',
    primaryKey: '_id',
    properties: {
      _id: 'int',
      pid: 'int',
      pYear: 'int',
      pVersion: 'int',
      pRollCorr: 'int',
      propType: 'string',
      asCode: 'string',
      block: 'string',
      tract: 'string',
      lot: 'string',
      mhSpaceNum: 'string',
      condoUnit: 'string',
      additionalLegal: 'string',
      legalAcreage: 'double?',
      autoBuildLegal: 'string',
      geoID: 'string?',
      simpleGeo: 'string?',
      refID1: 'string?',
      refID2: 'string?',
      massCreatedFrom: 'int',
      templateProperty: 'string?',
      templateDesc: 'string?',
      dba: 'string?',
      altDBA: 'string?',
      mortgageCoID: 'int?',
      mortgageCoAcctID: 'string?',
      effectiveSizeAcres: 'double?',
      legalDescription: 'string?',
      mapID: 'string?',
      mapsco: 'string?',
      propReference: 'string?',
      referenceDesc: 'string?',
      inactive: 'string?', 
      inactiveDt: 'string?',
      propCreateDt: 'string?',
      apprCompanyID: 'int',
      marketArea: 'string?',
      useCd: 'string?',
      zoning: 'string?',
      sicCd: 'string?',
      landValue: 'int?',
      improvementValue: 'int?',
      marketValue: 'int?',
      landHomesitePct: 'double?',
      structureHomesitePct: 'double?',
      ownerID: 'int?',
      ownerPct: 'double?',
      name: 'string?',
      nameSecondary: 'string?',
      firstName: 'string?',
      lastName: 'string?',
      spouseFirstName: 'string?',
      spouseLastName: 'string?',
      primarySitus: 'string?',
      streetNum: 'string?',
      streetName: 'string?',
      streetPrimary: 'string?',
      streetPrefix: 'string?',
      streetSuffix: 'string?',
      streetSecondary: 'string?',
      city: 'string?',
      state: 'string?',
      zip: 'string?',
      country: 'string?',
      international: 'string?',
      lastUpdated: 'date',
      // comments: 'Comment[]',
      // situsAddresses: 'Situs[]',
      // valuations: 'Valuation[]',
    }
  },

  // User: {
  //   name: 'User',
  //   primaryKey: '_id',
  //   properties: {
  //     _id: 'string',
  //     userId: 'string',
  //     firstName: 'string',
  //     lastName: 'string',
  //     email: 'string',
  //   }
  // },

  // Comment: {
  //   name: 'Comment',
  //   primaryKey: '_id',
  //   properties: {
  //     property: {
  //       type: 'linkingObjects',
  //       objectType: 'Property',
  //       property: 'comments',
  //     },
  //     _id: 'int',
  //     noteID: 'int',
  //     pID: 'int',
  //     content: 'string',
  //     createDt: 'date',
  //     createdBy: 'string?',
  //     updateDt: 'date?',
  //     updatedBy: 'string?',
  //   }
  // },
  
//   Situs: {
//     name: 'Situs',
//     primaryKey: '_id',
//     properties: {
//       property: {
//         type: 'linkingObjects',
//         objectType: 'Property',
//         property: 'situsAddresses',
//       },
//       _id: 'int',
//       situsAddressID: 'int',
//       pid: 'int',
//       pYear: 'int',
//       pVersion: 'int',
//       pRollCorr: 'int',
//       primarySitus: 'bool',
//       streetNum: 'string?',
//       streetPrefix: 'string?',
//       streetName: 'string?',
//       streetSecondary: 'string?',
//       streetSuffix: 'string?',
//       city: 'string',
//       state: 'string',
//       zip: 'string',
//       createDt: 'date',
//       createdBy: 'string?',
//       updateDt: 'date?',
//       updatedBy: 'string?',
//     }
//   },

//   Valuation: {
//     name: 'Valuation',
//     primaryKey: '_id',
//     properties: {
//       property: {
//         type: 'linkingObjects',
//         objectType: 'Property',
//         property: 'valuations',
//       },
//       _id: 'int',
//       pValuationID: 'int',
//       pid: 'int',
//       pYear: 'int',
//       pVersion: 'int',
//       pRollCorr: 'int',
//       valueType: 'string?',
//       value: 'int?',
//       landValue: 'int?',
//       structureValue: 'int?',
//       newValue: 'int?',
//       landHomesitePct: 'double?',
//       structureHomesitePct: 'double?',
//       newValueHomesitePct: 'double?',
//       pctAllocation: 'double?',
//       amtAllocation: 'double?',
//       notes: 'string?',
//       createDt: 'date',
//       updateDt: 'date?',
//       costApproachValuations: 'ValuationsCostApproach[]',
//     }
//   },

//   ValuationsCostApproach: {
//     name: 'ValuationsCostApproach',
//     primaryKey: '_id',
//     properties: {
//       valuation: {
//         type: 'linkingObjects',
//         objectType: 'Valuation',
//         property: 'costApproachValuations',
//       },
//       _id: 'int',
//       pCostID: 'int',
//       pValuationID: 'int',
//       grossLivingArea: 'int?',
//       livingArea: 'int?',
//       propUse: 'string?',
//       stateCd: 'string?',
//       quality: 'int?',
//       propCondition: 'int?',
//       yearBuilt: 'double?',
//       effYearBuilt: 'double?',
//       age: 'int?',
//       landValue: 'int?',
//       structureValue: 'int?',
//       improvements: 'Improvement[]',
//       land: 'Land[]',
//     },
//   },

//   Improvement: {
//     name: 'Improvement',
//     primaryKey: '_id',
//     properties: {
//       ValuationCostApproach: {
//         type: 'linkingObjects',
//         objectType: 'ValuationsCostApproach',
//         property: 'improvements',
//       },
//       _id: 'int',
//       pImprovementID: 'int',
//       pCostID: 'int',
//       imprvType: 'string?',
//       stateCd: 'string?',
//       homesite: 'bool?',
//       homesiteOverride: 'bool?',
//       homesitePct: 'double?',
//       imprvDescription: 'string?',
//       imprvComment: 'string?',
//       style: 'string?',
//       class: 'string?',
//       quality: 'string?',
//       structure: 'string?',
//       finishoutPct: 'double?',
//       stories: 'int?',
//       units: 'int?',
//       imprvCondition: 'string?',
//       actualYearBuilt: 'int?',
//       effYearBuilt: 'int?',
//       deprec: 'double?',
//       deprecGood: 'double?',
//       costLocalValue: 'int?',
//       costExternalValue: 'int?',
//       costExternalSource: 'string?',
//       costSource: 'string?',
//       economicAdj: 'double?',
//       economicNote: 'string?',
//       functionalAdj: 'double?',
//       functionalNote: 'string?',
//       physicalAdj: 'double?',
//       physicalNote: 'string?',
//       pctComplete: 'double?',
//       pctCompleteNote: 'string?',
//       selectedCostValue: 'int?',
//       imprvModifier: 'double?',
//       imprvAreaModifier: 'double?',
//       adjustedValue: 'int?',
//       flatValue: 'int?',
//       valueSource: 'string?',
//       improvementValue: 'int?',
//       createdBy: 'string?',
//       createDt: 'date?',
//       updatedBy: 'string?',
//       updateDt: 'date?',
//       temp_pID: 'int?',
//       temp_pYear: 'int?',
//       temp_vImprvID: 'int?',
//       copyFromID: 'int?',
//       lastUpdate: 'string?',
//       recalcDt: 'date?',
//       recalcBy: 'string?',
//       fromImprovementID: 'int?',
//       pricingModel: 'int?',
//       sketchID: 'int?',
//       calcAdjustmentFactor: 'double?',
//       calcAdjustmentAmount: 'int?',
//       calcAdjustmentPctWoutDeprec: 'double?',
//       improvementNotes: 'ImprovementNote[]',
//       improvementDetails: 'ImprovementDetail[]',
//     },
//   },

//   ImprovementNote: {
//     name: 'ImprovementNote',
//     primaryKey: '_id',
//     properties: {
//       Improvement: {
//         type: 'linkingObjects',
//         objectType: 'Improvement',
//         property: 'improvementNotes',
//       },
//       _id: 'int',
//       pNoteID: 'int',
//       pImprovementID: 'int',
//       type: 'string?',
//       content: 'string?',
//       createDt: 'date',
//       createdBy: 'string?',
//       updateDt: 'date?',
//       updatedBy: 'string?',
//     }
//   },

//   Land: {
//     name: 'Land',
//     primaryKey: '_id',
//     properties: {
//       ValuationCostApproach: {
//         type: 'linkingObjects',
//         objectType: 'ValuationsCostApproach',
//         property: 'land',
//       },
//       _id: 'int',
//       pLandID: 'int',
//       pCostID: 'int',
//       landType: 'string?',
//       stateCd: 'string?',
//       class: 'string?',
//       homesite: 'bool?',
//       influence: 'string?',
//       landDescription: 'string?',
//       sizeSqft: 'double?',
//       sizeUseableSqft: 'double?',
//       sizeAcres: 'double?',
//       sizeUseableAcres: 'double?',
//       sizeLot: 'int?',
//       sizeEffectiveFront: 'double?',
//       sizeWidthFront: 'double?',
//       sizeWidthBack: 'double?',
//       sizeEffectiveDepth: 'double?',
//       sizeDepthRight: 'double?',
//       sizeDepthLeft: 'double?',
//       effectiveAcresOverride: 'bool?',
//       sizeEffectiveAcresOverride: 'double?',
//       mktMethod: 'string?',
//       mktModel: 'int?',
//       mktUnitPriceSelection: 'string?',
//       mktModelUnitPrice: 'double?',
//       mktSpecialUnitPrice: 'double?',
//       mktEconomicAdj: 'double?',
//       mktEconomicNote: 'string?',
//       mktFunctionalAdj: 'double?',
//       mktFunctionalNote: 'string?',
//       mktPhysicalAdj: 'double?',
//       mktPhysicalNote: 'string?',
//       mktLandModifier: 'double?',
//       applyLandAreaModifier: 'bool?',
//       mktLandAreaModifier: 'double?',
//       mktCalculatedValue: 'int?',
//       mktAdjValue: 'int?',
//       mktFlatValue: 'int?',
//       mktFlatValueNote: 'string?',
//       mktValueMethod: 'string?',
//       mktValue: 'int?',
//       mktNewValueIndicator: 'bool?',
//       mktNewValueYear: 'double?',
//       suApply: 'bool?',
//       suUseCd: 'string?',
//       suApplyYr: 'double?',
//       suLate: 'bool?',
//       suType: 'string?',
//       suSoilType: 'string?',
//       suModel: 'int?',
//       suMethod: 'string?',
//       suUnitPriceSelection: 'string?',
//       suModelUnitPrice: 'double?',
//       suSpecialUnitPrice: 'double?',
//       suValueMethod: 'string?',
//       suCalculatedValue: 'int?',
//       suFlatValue: 'int?',
//       suValue: 'int?',
//       suExclusionValue: 'int?',
//       suNewValueIndicator: 'bool?',
//       suNewValueYear: 'double?',
//       suConvertDt: 'date?',
//       su78Value: 'int?',
//       su78ValuePct: 'double?',
//       suRestrictedUse: 'string?',
//       suRestrictedUseValue: 'int?',
//       suPreRestrictedUseValue: 'int?',
//       suHarvestDt: 'date?',
//       createdBy: 'string?',
//       createDt: 'date?',
//       updatedBy: 'string?',
//       updateDt: 'date?',
//       recalcDt: 'date?',
//       recalcBy: 'string?',
//       fromLandID: 'int?',
//       calcAdjustmentFactor: 'double?',
//       calcAdjustmentAmount: 'int?',
//       calcLandHSValue: 'int?',
//       calcLandNHSValue: 'int?',
//       calcSULandMktValue: 'int?',
//       mktClass: 'string?',
//       suClass: 'string?',
//       legacyValue: 'int?',
//       landNotes: 'LandNote[]',
//     },
//   },

//   LandNote: {
//     name: 'LandNote',
//     primaryKey: '_id',
//     properties: {
//       Land: {
//         type: 'linkingObjects',
//         objectType: 'Land',
//         property: 'landNotes',
//       },
//       _id: 'int',
//       pNoteID: 'int',
//       pLandID: 'int',
//       content: 'string?',
//       createDt: 'date',
//       createdBy: 'string?',
//       updateDt: 'date?',
//       updatedBy: 'string?',
//     }
//   },

//   ImprovementDetail: {
//     name: 'ImprovementDetail',
//     primaryKey: '_id',
//     properties: {
//       Improvement: {
//         type: 'linkingObjects',
//         objectType: 'Improvement',
//         property: 'improvementDetails',
//       },
//       _id: 'int',
//       pDetailID: 'int',
//       pImprovementID: 'int',
//       imprvDetailType: 'string?',
//       characteristicOverride: 'bool',
//       style: 'string?',
//       quality: 'string?',
//       class: 'string?',
//       structure: 'string?',
//       finishoutPct: 'double?',
//       units: 'int?',
//       stories: 'int?',
//       conditionOverride: 'bool',
//       imprvCondition: 'string?',
//       actualYearBuilt: 'int?',
//       effYearBuilt: 'int?',
//       age: 'int?',
//       deprec: 'double?',
//       deprecGood: 'double?',
//       pricingModel: 'int?',
//       pricingModelNote: 'string?',
//       pricingUnitPrice: 'double?',
//       specialUnitPrice: 'double?',
//       specialUnitPriceNote: 'string?',
//       pricingMethod: 'string?',
//       sketchArea: 'int?',
//       manualArea: 'int?',
//       areaSource: 'string?',
//       area: 'int?',
//       wallHeightInterior: 'double?',
//       wallHeightExterior: 'double?',
//       dimensionLength: 'double?',
//       dimensionWidth: 'double?',
//       loadingDockHeight: 'double?',
//       length: 'double?',
//       width: 'double?',
//       height: 'double?',
//       adjOverride: 'bool',
//       economicAdj: 'double?',
//       economicNote: 'string?',
//       functionalAdj: 'double?',
//       functionalNote: 'string?',
//       physicalAdj: 'double?',
//       physicalNote: 'string?',
//       pctComplete: 'double?',
//       pctCompleteNote: 'string?',
//       imprvDetailModifier: 'double?',
//       replacementCostNew: 'int?',
//       adjustedValue: 'int?',
//       flatValue: 'int?',
//       valueSource: 'string?',
//       improvementDetailValue: 'int?',
//       createdBy: 'string?',
//       createDt: 'date',
//       updatedBy: 'string?',
//       updateDt: 'date?',
//       recalcDt: 'date?',
//       recalcBy: 'string?',
//       fromDetailID: 'int?',
//       perimeter: 'int?',
//       nodes: 'int?',
//       arcs: 'int?',
//       calcBaseUnitPrice: 'double?',
//       calcFeatureUnitPrice: 'double?',
//       calcFeatureAmount: 'int?',
//       calcAdjustmentFactor: 'double?',
//       calcAdjustmentAmount: 'int?',
//       calcAdjustmentPctWoutDeprec: 'double?',
//     }
//   },

//   Codefile: {
//     name: 'Codefile',
//     primaryKey: '_id',
//     properties: {
//       _id: 'int',
//       codeFileYear: 'int',
//       codeFileType: 'string',
//       codeFileName: 'string',
//       codeName: 'string',
//       codeDescription: 'string?',
//       codeDefinition: 'string?',
//       createdBy: 'string?',
//       createDt: 'date?',
//       updatedBy: 'string?',
//       updateDt: 'date?',
//       active: 'bool',
//       isSystem: 'bool',
//     }
//   },

//   Model: {
//     name: 'Model',
//     primaryKey: '_id',
//     properties: {
//       _id: 'int',
//       modelID: 'int',
//       modelYr: 'int',
//       modelCode: 'string',
//       modelName: 'string',
//       modelType: 'string?',
//       createdBy: 'string?',
//       createDt: 'date?',
//       updatedBy: 'string?',
//       updateDt: 'date?',
//     }
//   },

//   ChangeSession: {
//     name: 'ChangeSession',
//     primaryKey: '_id',
//     properties: {
//       _id: 'string',
//       sessionId: 'string',
//       pid: {
//         type: 'int',
//         indexed: true,
//       },
//       pVersion: 'int',          // future use, version of property record at start
//       status: {
//         type: 'string',
//         indexed: true,
//       },
//       createdBy: 'string',
//       createDt: 'date',         // timestamp when the session began
//       syncDate: 'date?',        // timestamp when the change set has been sync'd
//       reconcileDate: 'date?',   // timestamp when approver submitted reconciliation
//       changes: 'Change[]',
//     }
//   },

//   Change: {
//     name: 'Change',
//     primaryKey: '_id',
//     properties: {
//       ChangeSession: {
//         type: 'linkingObjects',
//         objectType: 'ChangeSession',
//         property: 'changes',
//       },
//       _id: 'string',
//       changeId: 'string',
//       changeType: 'int',        // INSERT, UPDATE, DELETE
//       class: {                  // name of schema classes above
//         type: 'string',
//         indexed: true,
//       },
//       objectKey: 'string?',     // key of the object that changed
//       payload: 'string?',       // stringified object properties or change object
//       createDt: 'date',
//     }
//   }
}
